name: Output information 
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context # GitHub 컨텍스트에 접근하여 정보를 확인할 수 있다.
        run: echo "${{ toJSON(github) }}" # GitHub Actions에서 지원하는 함수와 표현식
